name: Build and Test fft-convolution

on:
  push:
    branches: [ main ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Check Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --check
  
  build:
    name: Build and Test
    needs: format
    strategy:
      matrix:
        os: [macos-14, macos-15, ubuntu-22.04]
        include:
          - os: macos-14
            target: x86_64-apple-darwin
          - os: macos-15
            target: aarch64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --release --target ${{ matrix.target }}

